pipeline {
    agent none

    stages {

        stage('Checkout') {
            agent { label 'agent-1' }

            steps {
                checkout scm
            }
        }

        stage('Build on Agent 1') {
            agent { label 'agent-1' }

            steps {
                dir('Project-Distributed-Jenkins/portfolio') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build on Agent 2') {
            agent { label 'agent-2' }

            steps {
                dir('Project-Distributed-Jenkins/portfolio') {
                    sh 'mvn clean package'
                }
            }
        }
    }
}
